#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [-f] <rev-list-args>"
	echo >&2 "  e.g."
	echo >&2 "  $0 HEAD~10.."
	echo >&2 "  $0 HEAD~5..master"
	exit 2
}

set -e

src="$(dirname "$(readlink -f "$0")")"

extra_args=
if test "$1" = -f
then
	extra_args=-f
	shift
fi

if [ $# -ne 1 ]
then usage
fi

rewrite_env_branch="$(git current-branch)"
if test "$rewrite_env_branch" = HEAD
then
	echo >&2 "$0: not on a branch"
	exit 1
fi

branch=$(echo "$1" | sed -n '/.*\.\.\(.*\)/s//\1/p')
if test -z "$branch"
then branch="$rewrite_env_branch"
fi

branch_path="$(git rev-parse --show-cdup).git/refs/heads/$branch"
if ! test -e "$branch_path"
then
	echo >&2 "$branch doesn't exist ($branch_path)"
	exit 1
fi

git filter-branch \
	$extra_args \
	--env-filter ". $src/git-rewrite-env-logic" \
	"$1"
