#!/bin/sh

if [ $# -ne 0 ]
then
	echo "Usage: $0" >&2
	exit 1
fi

tlog=/tmp/bundle.$$
echo > $tlog

cleanup(){
	ec=$?
	cat $tlog
	rm -f $tlog
	if [ $ec -ne 0 ]
	then echo >&2 "bundle error"
	fi
	exit $ec
}

branch_to_bundle(){
	echo "$(basename "$(pwd)").$(echo "$1" | tr / _)".bundle
}

trap cleanup EXIT

failed=0

git-ahead | while read n b r
do
	f=$(branch_to_bundle "$b")

	git bundle create "$f" origin/"$b".."$b" || exit $?
	echo "wrote $f" >> $tlog
done
if [ $? -ne 0 ]
then failed=1
fi

git-untracking | while read b
do
	f=$(branch_to_bundle "$b")

	mbase=$(git merge-base master "$b")

	git bundle create "$f" $mbase.."$b" || exit $?
	echo "wrote $f" >> $tlog
done
if [ $? -ne 0 ]
then failed=1
fi

exit $failed
