#!/bin/sh

if [ $# -ne 0 ]
then
	echo "Usage: $0" >&2
	exit 1
fi

git-ahead | while read b n
do
	f="$(basename "$(pwd)").$(echo "$b" | sed 's;/;_;g')"

	git bundle create "$f".bundle origin/"$b".."$b"
done
