#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [-N]"
	echo >&2 " -N: number of checkouts to show"
	exit 1
}

n=-5

if [ $# -eq 1 ]
then
	n="$1"
	if ! echo "$n" | grep '^-[0-9]\+$' >/dev/null
	then usage
	fi
elif [ $# -ne 0 ]
then usage
fi

headlog="$(git rev-parse --git-dir)"/logs/HEAD
n=$(echo "$n" | sed 's/^-//')

grep 'checkout: moving from .* to' "$headlog" \
	| sed 's;.*> \([0-9]*\) [+-][0-9]*.* to \([^ ]*\)$;\1 \2;' \
	| grep -v ' [0-9a-f]*$' \
	| perl -e '
my $max = shift;
my %entries;

while(<>){
	chomp;
	$entries{$_} = 1;
}

for(sort { $a <=> $b } keys %entries){
	last if($max-- == 0);
	/^[0-9]+ (.*)$/;
	print "$1\n";
}
' $n
