#!/bin/sh

usage(){
	echo "Usage: $0" >&2
	exit 1
}

if [ $# -ne 0 ]
then usage
fi

revcnt(){
	git rev-list --count "$1"
}

show_ab(){
	rvcnt=`revcnt "${2}..${3}" `
	if [ $rvcnt != 0 ]
	then echo "$1 $rvcnt $4"
	fi
}

set -e

git branch \
	| sed 's;^\** *;;' \
	| while read local
	do
		local_upstream="$local@{u}"

		if ! remote="$(
			git rev-parse --abbrev-ref --symbolic-full-name "$local_upstream" 2>/dev/null)"
		then
			echo >&2 "$local has no upstream"
			continue
		fi

		base=`git merge-base "$local" "$remote"`
		show_ab 'ahead'  "$base" "$local"  "$local $remote"
		show_ab 'behind' "$base" "$remote" "$local $remote"
	done
