#!/usr/bin/perl

sub usage {
    warn "Usage: $0 [--head=...] [git-log-arguments] rev\n";
    exit 2;
}

if(@ARGV == 0){
    usage();
}

my $head = "HEAD";
my @args;
for(@ARGV){
	if(/^--head=(.*)/){
		$head = $1;
		if(length $head == 0){
			print STDERR "--head argument is empty\n";
			usage();
		}
	}else{
		push @args, $_;
	}
}

my $rev = pop @args;

chomp(my $mergebase = `git merge-base $rev $head`);
exit 1 unless length $mergebase;

exit(system('git', 'log', @args, "$mergebase..$head"));
