#!/bin/sh

if test $# -ne 0
then
	echo >&2 "Usage: $0"
	exit 2
fi

red=$(printf '\x1b[31m')
blue=$(printf '\x1b[34m')
clear=$(printf '\x1b[0m')

cat <<!
${red}git checkout [-p] tree -- pathspec
${blue}git restore [-p] -s tree pathspec

${blue}git restore --staged/-S ... # apply change to index only

${clear}--------

${red}git checkout [--detach] branch
${blue}git switch [--detach] branch

${red}git checkout -b name commit
${blue}git switch -c name commit # -C to overwrite existing branch
!
