#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [remote]"
	exit 1
}

r=origin

if [ $# -eq 1 ]
then r="$1"
elif [ $# -ne 0 ]
then usage
fi

git branch -r   \
	| grep "$r"/  \
	| sed /HEAD/d \
	| xargs git log '--pretty=format:%an %ae' \
	| sort        \
	| uniq
