#!/bin/sh

pushtype=publish
dry=
flags=
if [ "$1" = -n ]
then
	dry=echo
	shift
fi
if [ "$1" = -n ]
then
	dry=
	flags=-n
	shift
fi

if [ "$1" = -d ]
then
	pushtype=drafts
	shift
fi

if [ $# -ne 3 ]
then
	echo >&2 "Usage: $0 [-n] [-n] [-d] remote refspec target-branch"
	echo >&2 "-n specified once will echo the git push and tag commands"
	echo >&2 "-n specified twice will pass the dry run through to git-push"
	echo >&2 "-d: push to refs/drafts"
	exit 1
fi

remote="$1"
refsp="$2"
target="$3"

set -e

$dry git push $flags "$remote" "$refsp":refs/$pushtype/"$target"
if [ -z "$flags" ]
then $dry git tag -f gerrit/last-pushed/"$target" "$refsp"
fi
