#!/bin/sh

set -e

verbose=no

read epoch offset <<!
$GIT_AUTHOR_DATE
!
old=$GIT_AUTHOR_DATE

when=$(date -d "$epoch" | tr : ' ')

read day datenum month hr min sec zone year <<!
$when
!

if test $hr -lt 19 && test $day != Sun && test $day != Sat
then
	if ! which shuf >/dev/null
	then
		shuf(){
			perl -e '
				use List::Util qw(shuffle);
				print shuffle <>;
			'
		}
	fi

	newhr=$(seq 19 23 | shuf | head -1)

	newdate="$day, $datenum $month $year $newhr:$min:$sec $zone"

	GIT_AUTHOR_DATE="@$(date -d "$newdate" +%s) $offset"

	if test $verbose = yes
	then
		echo "$when -> $newdate"
		echo "$old -> $GIT_AUTHOR_DATE"
	fi
fi

expected_email="$(git config user.email)"
GIT_AUTHOR_EMAIL="$expected_email"

GIT_AUTHOR_NAME="$(git config user.name)"

export GIT_AUTHOR_DATE
export GIT_AUTHOR_EMAIL
export GIT_AUTHOR_NAME

export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
