#!/bin/sh

if [ $# -ne 0 ]
then
	echo "Usage: $0" >&2
	exit 1
fi

b=$(git current-branch)

if [ "$b" = HEAD ]
then
	echo "detached HEAD"
else
	track=$(git config -l | grep "^branch\.$b.merge=" | sed 's;.*=refs/heads/;;')
	remote=$(git config -l | grep "^branch\.$b.remote=" | sed 's;.*=;;')

	ahead=$(git rev-list --count "$remote/$track..$b")
	behind=$(git rev-list --count "$b..$remote/$track")

	echo "$b..$remote/$track ahead $ahead behind $behind"
fi
