#!/bin/bash

if test $# -ne 2
then
	echo >&2 "Usage: $0 first-remote second-remote"
	exit 2
fi

first="$1"
second="$2"

remote_branch_hashes(){
	git branch -a \
		| grep "remotes/$1" \
		| sed /HEAD/d \
		| cut '-d ' -f3- \
		| xargs -I{} sh -c 'printf "%s " {}; git rev-parse {} 2>/dev/null' \
		| sed 's;^remotes/[^/]*/;;'
}

diff -U0 <(remote_branch_hashes $first) <(remote_branch_hashes $second)
