#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [--committer yyyy-mm-ddThh:mm:ss] yyyy-mm-ddThh:mm:ss [git-commit args...]"
	echo >&2 "--committer: Specify committer date (defaults to given author date)"
	exit 2
}

committer=
if test "$1" = --committer
then
	if test -z "$2"
	then usage
	fi
	committer="$2"
	shift 2
fi

if test $# -lt 1
then usage
fi

export GIT_AUTHOR_DATE="$1"
shift

if test -n "$committer"
then export GIT_COMMITTER_DATE="$committer"
else export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"
fi

git commit \
	--date="$GIT_COMMITTER_DATE" \
	"$@"
