#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [-n] [-n] [-d] [-r=N,a,b,c] remote refspec target-branch"
	echo >&2 "  -n specified once will echo the git push and tag commands"
	echo >&2 "  -n specified twice will pass the dry run through to git-push"
	echo >&2 "  -d: push to refs/drafts"
	echo >&2 "  -r: call gerrit set-reviewers with the count and names"
	exit 1
}

pushtype=publish
dry=
flags=
reviewers=

for arg
do
	if [ "$arg" = -n ]
	then
		if [ "$dry" = echo ]
		then
			dry=
			flags=-n
		else
			dry=echo
		fi
	elif [ "$arg" = -d ]
	then
		pushtype=drafts
		shift
	elif echo "$arg" | grep '^-r=' >/dev/null
	then
		reviewers="$(echo "$arg" | sed 's/^-r=//')"
	else
		break
	fi
	shift
done

if [ $# -ne 3 ]
then usage
fi
remote="$1"
refsp="$2"
target="$3"

set -e

if ! $dry git push $flags "$remote" "$refsp":refs/$pushtype/"$target"
then
	printf >&2 '\e[1;31mFAILURE!!!!!!!!!!!!!!!!!!!\e[m\n'
	exit 1
fi

if [ -z "$flags" ]
then $dry git tag -f gerrit/last-pushed/"$target" "$refsp"
fi

if [ -n "$reviewers" ]
then
	review_n="$(echo "$reviewers" | sed 's/^\([^,]*\),.*/\1/')"
	review_arg="$(echo "$reviewers" \
		| sed 's/^[^,]*,//' \
		| tr ',' '\n' \
		| sed 's/^/-a /')"

	$dry gerrit set-reviewers $review_arg -- $(git rev-list -"$review_n" "$refsp")
fi
