#!/bin/sh

if [ $# -ne 1 ]
then
	echo "Usage: $0 [ahead|behind]" >&2
	exit 1
fi

git branch -v | \
	sed 's/^. *//'            | \
  perl -e '
my $type = shift;

while(<STDIN>){
	if(m@([^ ]+) +[0-9a-f]+ \[([^]]+)\]@){
		my($branch,$where) = ($1, $2);
		for(split /, */, $where){
			print "$branch $1\n" if $_ =~ /^$type ([0-9]+)/;
		}
	}
}' "$1"
