#!/bin/sh

if [ $# -ne 1 ]
then
	echo >&2 "Usage: $0 target"
	echo >&2 "target: 'origin/\$b' or 'master'"
	exit 1
fi

for b in `git branch -v|grep -F '[behind '|sed 's/\* *//'|sed 's/ .*//'`
do git co $b && VISUAL=true git merge $(eval echo $1) || exit $?
done

