#!/bin/sh

usage(){
	echo "Usage: $0" >&2
	exit 1
}

if [ $# -ne 0 ]
then usage
fi

revcnt(){
	git rev-list --count "$1"
}

show_ab(){
	rvcnt=`revcnt "${2}..${3}" `
	if [ $rvcnt != 0 ]
	then
		printf '%s \e[36m%s \e[33m%s\e[m\n' "$1" "$rvcnt" "$4"
	fi
}

set -e

git branch \
	| sed 's;^\** *;;' \
	| while read local
	do
		local_upstream="$local@{u}"

		if ! remote="$(
			git rev-parse --abbrev-ref --symbolic-full-name "$local_upstream" 2>/dev/null)"
		then
			printf >&2 '\e[1;30m%s has no upstream\e[m\n' "$local"
			continue
		fi

		base=`git merge-base "$local" "$remote"`
		show_ab '[32mahead[m'  "$base" "$local"  "$local $remote"
		show_ab '[31mbehind[m' "$base" "$remote" "$local $remote"
	done
