#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [-n] [-n] [-d] [-r=N,a,b,c] remote refspec target-branch"
	echo >&2 "  -n specified once will echo the git push and tag commands"
	echo >&2 "  -n specified twice will pass the dry run through to git-push"
	echo >&2 "  -d: push to refs/drafts"
	exit 1
}

pushtype=publish
dry=
flags=

for arg
do
	if [ "$arg" = -n ]
	then
		if [ "$dry" = echo ]
		then
			dry=
			flags=-n
		else
			dry=echo
		fi
	elif [ "$arg" = -d ]
	then
		pushtype=drafts
		shift
	else
		break
	fi
	shift
done

if [ $# -ne 3 ]
then usage
fi
remote="$1"
refsp="$2"
target="$3"

set -e

$dry git push $flags "$remote" "$refsp":refs/$pushtype/"$target"
if [ -z "$flags" ]
then $dry git tag -f gerrit/last-pushed/"$target" "$refsp"
fi
