#!/bin/sh

usage(){
	echo >&2 "Usage: $0 refspec"
	exit 2
}

if test $# -ne 1 || echo "$1" | grep -q '^-'
then usage
fi

merges=$(git rev-list --merges --abbrev-commit "$1")
if test -n "$merges"
then
	echo >&2 "$0: revset \"$1\" contains merges:"
	echo >&2 "$merges"
	exit 1
fi

git log --pretty=format:'%h %at %ct' "$1" \
	| perl -nae '
	use POSIX qw(strftime);

	sub iso {
		return strftime("%Y-%m-%dT%H:%M:%SZ", gmtime shift);
	}

	BEGIN {
		$prev_ct = undef;
		$prev_ci = undef;
		$ec = 0;
	}

	($hash, $at, $ct) = @F;

	if ($ct < $at) {
		warn "$hash: committer date (" . iso($ct) . ") < author date (" . iso($at) . ")\n";
		$ec = 1;
	}

	if (defined $prev_ct && $ct > $prev_ct) {
		warn "$hash: committer date (" . iso($ct) . ") < previous committer date (" . iso($prev_ct) . " / $prev_ci)\n";
		$ec = 1;
	}

	$prev_ct = $ct;
	$prev_ci = $hash;
	END { exit $ec }
'
