#!/bin/sh

if [ $# -ne 0 ]
then
	echo "Usage: $0" >&2
	exit 1
fi

git-ahead | while read b n
do
	f="$(basename "$(pwd)").$(echo "$b" | tr / _)".bundle

	git bundle create "$f" origin/"$b".."$b"

	echo "wrote $f"
done
