#!/bin/sh

if [ $# -ne 0 ]
then
	echo "Usage: $0" >&2
	exit 1
fi

git branch -v               | \
	grep 'behind [0-9]\+\]' | \
	sed 's/^. *//'            | \
	sed 's/^\([^ ]*\).*behind \([0-9]*\)\].*/\1 \2/'
