#!/usr/bin/perl

use strict;
use warnings;
use constant {
	DEBUG => ($ENV{DEBUG} || "") eq 1,
};

sub usage {
	print STDERR "Usage: $0 [-r revset] [-i] [-j jobs] pattern [fileset]\n";
	exit 2;
}

my $pat;
my $revset;
my $fileset;
my $grep_flags;
my $job_limit = 4;

while(@ARGV){
	$_ = shift;

	if($_ eq '-i'){
		$grep_flags = $_;
	}elsif($_ eq '-r'){
		usage() if defined $revset || @ARGV == 0;

		$revset = shift;
	}elsif($_ eq '-j'){
		usage() if @ARGV == 0;

		$job_limit = shift;
		usage() if $job_limit !~ /^[0-9]+$/ || $job_limit == 0;
	}elsif(/^-/){
		usage();
	}elsif(!defined $pat){
		$pat = $_;
	}elsif(!defined $fileset){
		$fileset = $_;
	}else{
		usage();
	}
}

$revset = "@" unless defined $revset;

sub forkexec_with_stdio {
	my($cmdlist, $r, $w) = @_;

	my $pid = fork();
	die "fork: $!" unless defined $pid;

	if($pid == 0){
		open STDIN, "<&", $r or die "dup: $!";
		close $r;
		open STDOUT, ">&", $w or die "dup: $!";
		close $w;
		exec @$cmdlist;
		die "exec $cmdlist->[0]: $!";
	}

	return $pid;
}

sub runpipe {
	my($input, $output, @cmds) = @_;

	my $carry_r;
	my %pids;
	my $last;

	for(my $i = 0; $i < @cmds; $i++){
		my $this_r;
		my $this_w;

		if($i == 0){
			open $this_r, '<&', $input or die "dup stdin: $!";
			die "logic error: have an initial carry pipe?" if defined $carry_r;
		}else{
			$this_r = $carry_r;
			$carry_r = undef;
		}
		if($i == $#cmds){
			open $this_w, '>&', $output or die "dup stdout: $!";
			die "logic error: have a final unconsumed carry pipe?" if defined $carry_r;
		}else{
			pipe $carry_r, $this_w or die "pipe: $!";
		}

		my $pid = forkexec_with_stdio($cmds[$i], $this_r, $this_w);
		$pids{$pid} = 1;
		$last = $pid;

		if(DEBUG){
			print STDERR "$0: spawned [" . join(", ", map { "\"$_\"" } @{$cmds[$i]}) . "], pid $pid\n";
		}

		close $this_w;
		close $this_r;
	}

	die "logic error: have an open read pipe" if defined $carry_r;

	return sub {
		my $ret;
		for my $candidate (keys %pids){
			my $reaped = waitpid $candidate, 0; # must wait for only pids that we're looking after
			my $ec = $? >> 8;
			my $no_children = $reaped == -1;
			die "logic error: no children to reap but have pids [" . join(", ", keys %pids) . "]" if $no_children;

			if(DEBUG){
				print STDERR "$0: finish(), reaped $reaped, ec $ec" . ($reaped == $last ? " (pipeline tail)" : "") . "\n";
			}

			my $elem = delete $pids{$reaped};
			die "$reaped isn't in the pid list" unless defined $elem;

			$ret = $ec if $reaped == $last;
		}

		if(DEBUG){
			print STDERR "$0: pipeline complete, ec=$ret\n";
		}

		die "final child in pipeline didn't exit?" unless defined $ret;
		return $ret;
	};
}

sub devnull {
	open my $in, '</dev/null' or die "open: $!";
	return $in;
}

sub lines {
	pipe my $r, my $w;

	my $dn = devnull();
	my $finish = runpipe($dn, $w, \@_);
	close $dn;
	close $w;

	return Job::new($r, $finish)->to_fn(retcheck => 1);
}

package Job {
	sub new {
		my($rh, $finish) = @_;

		return bless {
			finish => $finish,
			rh => $rh,
			ec => undef,
		};
	}

	sub fileno {
		return fileno(shift->{rh});
	}

	sub next_line {
		my $self = shift;

		my $fh = $self->{rh};
		my $line = <$fh>;
		return $line if defined $line;

		close $fh;
		$self->{ec} = $self->{finish}->();
		delete $self->{finish};
		return undef;
	}

	sub to_fn {
		my($self, %opts) = shift;

		return sub {
			my $line = $self->next_line();

			if(defined $line){
				chomp $line;
				return $line;
			}else{
				die "logic error" if defined $self->{finish};

				my $ec = $self->{ec};
				exit $ec if $opts{retcheck} && $ec;
			}
		};
	}
}

package GrepJob {
	sub new {
		my($job, $rev, $fname) = @_;

		return bless {
			job => $job,
			rev => $rev,
			fname => $fname,
			found => 0,
		};
	}

	sub next_line {
		my $self = shift;

		my $line = $self->{job}->next_line();

		return 0 unless defined $line;

		print "$self->{rev}:$self->{fname}:$line";
		$self->{found} = 1;
		return 1;
	}
}

sub reap_jobs {
	my($jobs, $finished) = @_;
	my @reaped;

	if(DEBUG){
		print STDERR "$0: reaping...\n";
	}

	while(@reaped == 0){
		my $rin = my $win = '';

		for my $gj (@$jobs) {
			vec($rin, $gj->{job}->fileno(), 1) = 1;
		}

		my $ein = $rin | $win;

		my $timeout = undef;
		my $nfound = select(my $rout = $rin, my $wout = $win, my $eout = $ein, $timeout);

		for(my $i = 0; $i < @$jobs; $i++){
			my $gj = $jobs->[$i];
			my $fileno = $gj->{job}->fileno();

			if(vec($rout, $fileno, 1) || vec($eout, $fileno, 1)){
				if(!$gj->next_line()){
					# finished, remove from list
					splice @$jobs, $i, 1;
					$i--;
					push @reaped, $gj;
				}
			}
		}
	}

	push @$finished, @reaped;

	if(DEBUG){
		print STDERR "$0: done reaping\n";
	}
}

my $rev_gen = lines(
	"jj", "log",
	"-r", $revset,
	"-T", 'change_id.short() ++ "\\n"',
	"-G",
);

my @jobs;
my @finished;
while(my $rev = $rev_gen->()){
	my $fname_gen = lines(
		"jj", "file", "list",
		"--revision", $rev,
		"--template", 'if(file_type == "file", path ++ "\\n")',
		defined $fileset ? ($fileset) : (),
	);

	while(my $fname = $fname_gen->()){
		pipe my $r, my $w;

		my $dn = devnull();
		my $finish = runpipe(
			$dn,
			$w,
			[
				"jj", "file", "show", "--revision", $rev, $fname,
			],
			[
				"grep", "-En", "--color=always", defined $grep_flags ? ($grep_flags) : (), $pat,
			],
		);
		close $dn;
		close $w;

		push @jobs, GrepJob::new(Job::new($r, $finish), $rev, $fname);
		reap_jobs(\@jobs, \@finished) while @jobs > JOB_LIMIT;
	}
}

reap_jobs(\@jobs, \@finished) while @jobs;

my $ec = 1;
for my $j (@finished){
	if($j->{found}){
		$ec = 0;
		last;
	}
	# ignore $j->{ec}
}
exit $ec;
