#!/bin/sh

filter=
case $# in
	0)
		;;
	1)
		if test "$1" = '--pick'
		then filter=p
		else usage
		fi
		;;
	*)
		usage
		;;
esac

while read cmd ci rest0 rest
do
	echo "$cmd $ci $rest0 $rest"

	if test "$cmd" = merge
	then
		if test "$ci" != -C
		then
			echo >&2 "assertion failure parsing merge"
			exit 1
		fi
		ci=$rest0
	else
		rest="$rest0 $rest"
	fi

	if ! echo "$ci" | grep -iE '^[0-9a-f]+$' >/dev/null
	then continue
	fi

	if test -n "$filter" && test "${cmd:0:1}" != "$filter"
	then continue
	fi

	git log -1 --date=iso-strict --format='%cd %ad' "$ci" \
		| (
			read date_c date_a && echo "x git commit-when --committer $date_c $date_a --amend --no-e"
		)
done
